# Generated by Django 2.2.14 on 2020-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_videos_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='genre',
            field=models.CharField(choices=[('REV', 'Review'), ('SCI', 'Science'), ('HUM', 'Humor')], default='REV', max_length=3),
        ),
    ]
