# Generated by Django 2.2.14 on 2020-08-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_videos_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date']},
        ),
    ]
