# Generated by Django 2.2.14 on 2020-08-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200812_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['published_date']},
        ),
    ]
