# Generated by Django 2.2.14 on 2020-08-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200812_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_date']},
        ),
    ]
